Bodin = ['love', 'energy', 'intelligence']
print(Bodin)
print(Bodin[0])
print(Bodin[1].title())
print(Bodin[-1])
print(Bodin[-2])
message = "Bodin is " + Bodin[1].title() + "."
print(message)
message = "Bodin is all " + Bodin[2].title() + "!"
print(message)
cars = ['honda', 'toyota', 'ford']
print(cars)
cars[2] = 'suburu'
print(cars)
cars.append('mustang')
print(cars)
cars.insert(0, 'kia')
print(cars)
cars.insert(2, 'chevorlet')
print(cars)
del cars[2]
print(cars)
popped_cars = cars.pop()
print(cars)
print(popped_cars)
print("The last car I owned was a " + popped_cars + ".")
first_car = cars.pop(0)
print("The first car I owned was a " + first_car + ".")
print(cars)
cars.remove('suburu')
print(cars)
invited = ['Edward O. Wilson', 'Oliver Sacks', 'Carl Sagan']
print(invited)
invited.remove('Oliver Sacks')
print(invited)
invited.insert(0, 'Oliver Sacks')
print(invited)
invited.insert(1, 'Galileo')
invited.append('David Attenborough')
print(invited)
invited.pop(-1)
print(invited)
invited.pop(0)
print(invited)
invited.pop(0)
print(invited)
del invited[0]
print(invited)
del invited[0]
print(invited)
flowers = ['maridgold', 'poppy', 'lilly']
flowers.sort()
print(flowers)
flowers.sort(reverse=True)
print(flowers)
print("Here is the list of flowers.")
print(sorted(flowers))
print("Here is another list.")
print(flowers)
print(len(flowers))
places_to_visit = ['Japan', 'France', 'Sweden', 'New Zealand']
print(places_to_visit)
sorted(places_to_visit)
print(sorted(places_to_visit))
print(places_to_visit)
places_to_visit.reverse()
print(places_to_visit)
print(len(places_to_visit))